# Area Analysis

Given a center coordinate and a few candidate target species, fetch Xeno-Canto metadata
for the area (50 km radius by default), build a per-species heatmap, and summarize what
else lives there — species/genus/family counts, co-occurring birds (`Recording.also`),
and time-bounded annotations (`Recording.annotation_set`).

**Prerequisites**
- `.env` in this folder with `XC_API_KEY=...`
- `uv sync` in `building/`
- `building/raw_dataset/taxonomy.csv` cached (gets fetched on first `building.taxonomy` import)

In [73]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [74]:
from pathlib import Path

import pyrootutils
from xenocanto3 import Quality

ROOT = pyrootutils.setup_root(
    search_from=Path.cwd(),
    indicator="pyproject.toml",
    pythonpath=True,
    dotenv=True,
)

# Parameters

In [75]:
LAT, LON = 48.8566, 2.3522            # Paris
RADIUS_KM = 50
SPECIES_NAMES = ["Emberiza calandra"]
MIN_QUALITY = Quality.B
MIN_RECORDINGS = 10                   # drop species with fewer than this many recordings in the area from the taxonomy breakdown

# BirdNET pass
MAX_BIRDNET_RECORDINGS = 500          # cap downloads — set to None to process all area recordings
BIRDNET_MIN_CONFIDENCE = 0.85         # detection threshold (download.py default is 0.92)

# Bounding box

In [76]:
from building.analysis import bbox_from_radius

bbox = bbox_from_radius(LAT, LON, RADIUS_KM)
print(f"bbox (lat_min, lon_min, lat_max, lon_max): {tuple(round(x, 4) for x in bbox)}")
print(f"lat span: {bbox[2] - bbox[0]:.3f}°   lon span: {bbox[3] - bbox[1]:.3f}°")

bbox (lat_min, lon_min, lat_max, lon_max): (48.4061, 1.6676, 49.3071, 3.0368)
lat span: 0.901°   lon span: 1.369°

# Per-species global heatmap

One toggleable layer per input species; the analysis area is overlaid as a black rectangle.

In [77]:
from building.analysis import fetch_species_global, recordings_to_df, build_heatmap, ANALYSIS_DIR

global_recs = await fetch_species_global(SPECIES_NAMES, min_quality=MIN_QUALITY)
per_species_df = {name: recordings_to_df(recs) for name, recs in global_recs.items()}

for name, df in per_species_df.items():
    print(f"{name:30s} {len(df):5d} recordings (with coords: {df['lat'].notna().sum()})")

heatmap = build_heatmap(per_species_df, center=(LAT, LON), bbox=bbox)
ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)
heatmap.save(str(ANALYSIS_DIR / "heatmap.html"))
heatmap

Emberiza calandra                229 recordings (with coords: 228)

# Recordings inside the area

In [78]:
from building.analysis import fetch_area_recordings

area_recs = await fetch_area_recordings(bbox, min_quality=MIN_QUALITY)
area_df = recordings_to_df(area_recs)
print(f"{len(area_df)} recordings, {area_df['scientific_name'].nunique()} unique species")

764 recordings, 145 unique species

# Are the target species present in the area?

In [79]:
from building.analysis import presence_in_area

presence_in_area(SPECIES_NAMES, area_df)

     scientific_name  recordings_in_area qualities  mean_length_sec
0  Emberiza calandra                   2         A             59.0

# Taxonomy breakdown of the area

How many orders / families / genera / species does the area hold? Useful for scoping a future training collection.

In [80]:
from building.analysis import taxonomy_breakdown

tax = taxonomy_breakdown(area_df, min_recordings=MIN_RECORDINGS)
totals = tax["totals"].iloc[0]
print(
    f"{totals['n_recordings']} recordings  |  "
    f"{totals['n_species']} species across {totals['n_genera']} genera, "
    f"{totals['n_families']} families, {totals['n_orders']} orders"
    f"  (species with ≥ {MIN_RECORDINGS} recordings)"
)
if totals["n_unmatched_in_taxonomy"]:
    print(f"({totals['n_unmatched_in_taxonomy']} recordings could not be matched to the eBird taxonomy)")
tax["totals"]

403 recordings  |  25 species across 20 genera, 17 families, 5 orders  (species with ≥ 10 recordings)
(41 recordings could not be matched to the eBird taxonomy)

,n_orders,n_families,n_genera,n_species,n_recordings,n_unmatched_in_taxonomy
0,5,17,20,25,403,41

In [81]:
tax["by_order"]

            order  species  recordings
0   Passeriformes       17         275
1             NaN        3          41
2    Strigiformes        2          30
3      Piciformes        1          22
4  Psittaciformes        1          21
5   Coraciiformes        1          14

In [82]:
tax["by_family"].head(20)

,order,family,species,recordings
0,Passeriformes,Sylviidae (Sylviid Warblers and Allies),3,48
1,NaN,NaN,3,41
2,Passeriformes,Acrocephalidae (Reed Warblers and Allies),2,39
3,Passeriformes,Muscicapidae (Old World Flycatchers),2,30
4,Passeriformes,Locustellidae (Grassbirds and Allies),2,28
5,Passeriformes,Motacillidae (Wagtails and Pipits),1,26
6,Piciformes,Picidae (Woodpeckers),1,22
7,Passeriformes,"Paridae (Tits, Chickadees, and Titmice)",1,22
8,Psittaciformes,Psittaculidae (Old World Parrots),1,21
9,Passeriformes,Regulidae (Kinglets),1,20
10,Passeriformes,Certhiidae (Treecreepers),1,18
11,Strigiformes,Tytonidae (Barn-Owls),1,17
12,Coraciiformes,Alcedinidae (Kingfishers),1,14
13,Strigiformes,Strigidae (Owls),1,13
14,Passeriformes,Troglodytidae (Wrens),1,12
15,Passeriformes,Turdidae (Thrushes and Allies),1,11
16,Passeriformes,Cisticolidae (Cisticolas and Allies),1,11
17,Passeriformes,"Fringillidae (Finches, Euphonias, and Allies)",1,10

In [83]:
tax["by_genus"].head(20)

,family,genus,species,recordings
0,NaN,NaN,3,41
1,Sylviidae (Sylviid Warblers and Allies),Curruca,2,34
2,Locustellidae (Grassbirds and Allies),Locustella,2,28
3,Acrocephalidae (Reed Warblers and Allies),Hippolais,1,26
4,Motacillidae (Wagtails and Pipits),Anthus,1,26
5,Picidae (Woodpeckers),Dendrocoptes,1,22
6,"Paridae (Tits, Chickadees, and Titmice)",Parus,1,22
7,Psittaculidae (Old World Parrots),Psittacula,1,21
8,Regulidae (Kinglets),Regulus,1,20
9,Certhiidae (Treecreepers),Certhia,1,18
10,Muscicapidae (Old World Flycatchers),Muscicapa,1,17
11,Tytonidae (Barn-Owls),Tyto,1,17
12,Alcedinidae (Kingfishers),Alcedo,1,14
13,Sylviidae (Sylviid Warblers and Allies),Sylvia,1,14
14,Muscicapidae (Old World Flycatchers),Erithacus,1,13
15,Strigidae (Owls),Athene,1,13
16,Acrocephalidae (Reed Warblers and Allies),Acrocephalus,1,13
17,Troglodytidae (Wrens),Troglodytes,1,12
18,Cisticolidae (Cisticolas and Allies),Cisticola,1,11
19,Turdidae (Thrushes and Allies),Turdus,1,11

# Co-occurring species

From each recording's `also` field — species heard in the background. Useful for discovering candidates that don't have their own recordings in the area but show up alongside others.

In [84]:
from building.analysis import co_occurrence_counts

co_occurrence_counts(area_df, top_n=30)

                       species  count
0            Fringilla coelebs     11
1       Phylloscopus collybita     10
2                Corvus corone      8
3      Troglodytes troglodytes      6
4                Turdus merula      6
5           Psittacula krameri      5
6           Sylvia atricapilla      4
7            Poecile palustris      4
8                  Parus major      4
9           Erithacus rubecula      3
10           Turdus philomelos      3
11                   Pica pica      3
12           Passer domesticus      3
13           Locustella naevia      3
14             Cuculus canorus      3
15             Chloris chloris      2
16               Columba oenas      2
17       Lophophanes cristatus      2
18     Acrocephalus scirpaceus      2
19       Luscinia megarhynchos      2
20                 Buteo buteo      2
21  Acrocephalus schoenobaenus      1
22          Scolopax rusticola      1
23              Turdus iliacus      1
24            Larus argentatus      1
25           Turdus viscivorus      1
26            Columba palumbus      1
27       Certhia brachydactyla      1
28         Garrulus glandarius      1
29              Sitta europaea      1

# Annotations

Time-bounded annotations attached to recordings (rare — most XC recordings are not annotated, but the ones that are can be useful training labels).

In [85]:
from building.analysis import annotation_summary

ann = annotation_summary(area_df)
print(f"{len(ann['annotations'])} annotations across {len(ann['by_species'])} species")
ann["by_species"].head(20)

0 annotations across 0 species

Empty DataFrame
Columns: [annotated_species, count]
Index: []

In [86]:
ann["annotations"].head(20)

Empty DataFrame
Columns: []
Index: []

# BirdNET pass on area recordings

Download the area's recordings and run BirdNET on each. Some birds are present in the audio but were not flagged by the recordist in XC's `also` field — BirdNET surfaces them.

Files cache to `raw_dataset/analysis/audio/` and downloads are skipped on re-run. Delete that folder to reclaim disk.

In [87]:
from building.analysis import birdnet_area_analysis

bn = await birdnet_area_analysis(
    area_df,
    max_recordings=MAX_BIRDNET_RECORDINGS,
    min_confidence=BIRDNET_MIN_CONFIDENCE,
)
det = bn["detections"]
print(
    f"{len(det)} detections across {det['xc_id'].nunique()} recordings  |  "
    f"{bn['by_species'].shape[0]} unique species detected  |  "
    f"{bn['hidden'].shape[0]} species not declared in XC `also`"
)

BirdNET analyse:   0%|          | 0/500 [00:00<?, ?it/s]

read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC528945.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC484893.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording XC484892.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC484891.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC386855.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC386854.mp3
read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording XC360691.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC360690.mp3
read_audio_data
read_audio_data: complete, read  38 chunks.
analyze_recording XC464102.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC560729.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC560723.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC560721.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC560710.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC560687.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC415060.mp3
read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording XC904390.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording XC541143.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC561731.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC597221.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording XC616975.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC541504.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC1100787.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC1078782.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC986953.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC821923.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC793318.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC637855.mp3
read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording XC154284.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC637068.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC927330.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC667805.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC793319.mp3
read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording XC647864.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC645260.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC522815.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording XC516972.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC516970.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording XC512864.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC512863.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC511438.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC539876.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC1098722.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC980189.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC692346.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC385895.mp3
read_audio_data
read_audio_data: complete, read  71 chunks.
analyze_recording XC931009.mp3
read_audio_data
read_audio_data: complete, read  45 chunks.
analyze_recording XC930735.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC914705.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC828038.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording XC143958.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC143957.mp3
read_audio_data
read_audio_data: complete, read  30 chunks.
analyze_recording XC143956.mp3
read_audio_data
read_audio_data: complete, read  59 chunks.
analyze_recording XC1071261.mp3
read_audio_data
read_audio_data: complete, read  31 chunks.
analyze_recording XC947067.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC930365.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC912403.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC793887.mp3
read_audio_data
read_audio_data: complete, read  82 chunks.
analyze_recording XC994509.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC522583.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC496570.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC496569.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC1041146.mp3
read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording XC669499.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC645769.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC645768.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC645767.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC645766.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC742074.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording XC670733.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC766994.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC986957.mp3
Labels loaded.
load model True
Model loaded.
Labels loaded.
load_species_list_model
Meta model loaded.
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording XC951743.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC931566.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC931553.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC909132.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC884888.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC883983.mp3
read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording XC821945.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC794603.mp3
read_audio_data
read_audio_data: complete, read  35 chunks.
analyze_recording XC702329.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC674177.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC634362.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC540471.mp3
read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording XC540470.mp3
read_audio_data
read_audio_data: complete, read  232 chunks.
analyze_recording XC476821.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC476819.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC476818.mp3
read_audio_data
read_audio_data: complete, read  136 chunks.
analyze_recording XC554149.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC554145.mp3
read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording XC554144.mp3
read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording XC554143.mp3
read_audio_data
read_audio_data: complete, read  26 chunks.
analyze_recording XC554142.mp3
read_audio_data
read_audio_data: complete, read  120 chunks.
analyze_recording XC539312.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC535444.mp3
read_audio_data
read_audio_data: complete, read  51 chunks.
analyze_recording XC535397.mp3
read_audio_data
read_audio_data: complete, read  38 chunks.
analyze_recording XC535396.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC535395.mp3
read_audio_data
read_audio_data: complete, read  75 chunks.
analyze_recording XC535389.mp3
read_audio_data
read_audio_data: complete, read  35 chunks.
analyze_recording XC535388.mp3
read_audio_data
read_audio_data: complete, read  274 chunks.
analyze_recording XC535386.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC540499.mp3
read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording XC540498.mp3
read_audio_data
read_audio_data: complete, read  47 chunks.
analyze_recording XC540497.mp3
read_audio_data
read_audio_data: complete, read  23 chunks.
analyze_recording XC447427.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC447426.mp3
read_audio_data
read_audio_data: complete, read  25 chunks.
analyze_recording XC882513.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC821830.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC692350.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC692349.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC692348.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC692347.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC606353.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC522991.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC522821.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC522820.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC522819.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC522818.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC490838.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC447433.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC767880.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC614213.mp3
read_audio_data
read_audio_data: complete, read  27 chunks.
analyze_recording XC556943.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC539359.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC539358.mp3
read_audio_data
read_audio_data: complete, read  46 chunks.
analyze_recording XC539357.mp3
read_audio_data
read_audio_data: complete, read  43 chunks.
analyze_recording XC539356.mp3
read_audio_data
read_audio_data: complete, read  29 chunks.
analyze_recording XC539355.mp3
read_audio_data
read_audio_data: complete, read  31 chunks.
analyze_recording XC536060.mp3
read_audio_data
read_audio_data: complete, read  21 chunks.
analyze_recording XC536058.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording XC533721.mp3
read_audio_data
read_audio_data: complete, read  11 chunks.
analyze_recording XC533720.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC533719.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC533717.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC533716.mp3
read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording XC528665.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC526346.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC522596.mp3
read_audio_data
read_audio_data: complete, read  59 chunks.
analyze_recording XC477936.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording XC471914.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC419883.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording XC419881.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC408949.mp3
read_audio_data
read_audio_data: complete, read  3 chunks.
analyze_recording XC147108.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC147107.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording XC540692.mp3
read_audio_data
read_audio_data: complete, read  109 chunks.
analyze_recording XC536062.mp3
read_audio_data
read_audio_data: complete, read  57 chunks.
analyze_recording XC535705.mp3
read_audio_data
read_audio_data: complete, read  47 chunks.
analyze_recording XC477934.mp3
read_audio_data
read_audio_data: complete, read  350 chunks.
analyze_recording XC475269.mp3
read_audio_data
read_audio_data: complete, read  58 chunks.
analyze_recording XC475265.mp3
read_audio_data
read_audio_data: complete, read  13 chunks.
analyze_recording XC147884.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC143094.mp3
read_audio_data
read_audio_data: complete, read  28 chunks.
analyze_recording XC785260.mp3
read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording XC541583.mp3
read_audio_data
read_audio_data: complete, read  60 chunks.
analyze_recording XC541579.mp3
read_audio_data
read_audio_data: complete, read  59 chunks.
analyze_recording XC541573.mp3
read_audio_data
read_audio_data: complete, read  50 chunks.
analyze_recording XC541559.mp3
read_audio_data
read_audio_data: complete, read  49 chunks.
analyze_recording XC541551.mp3
read_audio_data
read_audio_data: complete, read  75 chunks.
analyze_recording XC541548.mp3
read_audio_data
read_audio_data: complete, read  58 chunks.
analyze_recording XC541541.mp3
read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording XC541537.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC1098974.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC672898.mp3
read_audio_data
read_audio_data: complete, read  55 chunks.
analyze_recording XC672836.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording XC672835.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC672834.mp3
read_audio_data
read_audio_data: complete, read  125 chunks.
analyze_recording XC672833.mp3
read_audio_data
read_audio_data: complete, read  58 chunks.
analyze_recording XC670764.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC526971.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.
analyze_recording XC496588.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC485216.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording XC577476.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording XC563852.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC628902.mp3
read_audio_data
read_audio_data: complete, read  44 chunks.
analyze_recording XC628900.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC628899.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC628898.mp3
read_audio_data
read_audio_data: complete, read  17 chunks.
analyze_recording XC628895.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC971834.mp3
read_audio_data
read_audio_data: complete, read  36 chunks.
analyze_recording XC716806.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording XC600866.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC535796.mp3
read_audio_data
read_audio_data: complete, read  33 chunks.
analyze_recording XC534457.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC534454.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC528250.mp3
read_audio_data
read_audio_data: complete, read  112 chunks.
analyze_recording XC522975.mp3
read_audio_data
read_audio_data: complete, read  5 chunks.
analyze_recording XC522616.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC522614.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC516404.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC516402.mp3
read_audio_data
read_audio_data: complete, read  18 chunks.
analyze_recording XC511968.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC510543.mp3
read_audio_data
read_audio_data: complete, read  10 chunks.
analyze_recording XC509463.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC475257.mp3
read_audio_data
read_audio_data: complete, read  12 chunks.
analyze_recording XC475256.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC475255.mp3
read_audio_data
read_audio_data: complete, read  6 chunks.
analyze_recording XC474519.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC309170.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording XC143088.mp3
read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording XC490843.mp3
read_audio_data
read_audio_data: complete, read  14 chunks.
analyze_recording XC570741.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC568960.mp3
read_audio_data
read_audio_data: complete, read  15 chunks.
analyze_recording XC565121.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC561748.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC561746.mp3
read_audio_data
read_audio_data: complete, read  111 chunks.
analyze_recording XC561742.mp3
read_audio_data
read_audio_data: complete, read  35 chunks.
analyze_recording XC561732.mp3
read_audio_data
read_audio_data: complete, read  32 chunks.
analyze_recording XC560963.mp3
read_audio_data
read_audio_data: complete, read  4 chunks.
analyze_recording XC560962.mp3
read_audio_data
read_audio_data: complete, read  24 chunks.
analyze_recording XC541512.mp3
read_audio_data
read_audio_data: complete, read  7 chunks.
analyze_recording XC522579.mp3
read_audio_data
read_audio_data: complete, read  8 chunks.
analyze_recording XC161533.mp3
read_audio_data
read_audio_data: complete, read  19 chunks.
analyze_recording XC532224.mp3
read_audio_data
read_audio_data: complete, read  16 chunks.
analyze_recording XC522195.mp3
read_audio_data
read_audio_data: complete, read  9 chunks.
analyze_recording XC592894.mp3
read_audio_data
read_audio_data: complete, read  47 chunks.
analyze_recording XC537804.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC533768.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC519538.mp3
read_audio_data
read_audio_data: complete, read  2 chunks.
analyze_recording XC518443.mp3
read_audio_data
read_audio_data: complete, read  1 chunks.

### All detected species

In [88]:
bn["by_species"].head(40)

,detected_species,n_detections,n_recordings,n_undeclared,mean_conf,max_conf
67,Locustella naevia,598,14,1,0.974,1.000
15,Athene noctua,515,12,0,0.986,1.000
103,Sylvia borin,469,11,7,0.972,1.000
66,Locustella luscinioides,444,20,13,0.988,1.000
59,Hippolais polyglotta,284,27,7,0.965,1.000
76,Parus major,244,21,10,0.966,1.000
95,Regulus ignicapilla,226,21,33,0.977,1.000
1,Acrocephalus palustris,214,17,9,0.932,0.999
35,Curruca communis,203,21,2,0.961,1.000
45,Dendrocoptes medius,188,23,5,0.980,1.000
52,Falco tinnunculus,169,9,4,0.978,1.000
44,Dendrocopos major,157,9,13,0.943,0.997
93,Psittacula krameri,152,23,3,0.955,0.998
75,Oriolus oriolus,124,9,0,0.972,1.000
27,Cisticola juncidis,118,8,9,0.987,1.000
85,Phylloscopus trochilus,113,7,0,0.958,0.998
87,Picus viridis,97,14,6,0.982,1.000
6,Alauda arvensis,94,8,4,0.972,1.000
77,Periparus ater,81,3,0,0.965,0.999
91,Poecile palustris,77,9,10,0.974,1.000
40,Cyanistes caeruleus,77,8,21,0.946,0.999
39,Curruca undata,62,11,0,0.956,0.999
84,Phylloscopus sibilatrix,60,4,0,0.996,1.000
102,Sylvia atricapilla,60,15,11,0.936,0.996
109,Tyto alba,56,15,0,0.975,1.000
68,Lophophanes cristatus,54,8,4,0.964,1.000
92,Psittacula eupatria,53,6,2,0.981,1.000
5,Aix galericulata,51,6,0,0.969,1.000
14,Asio otus,43,2,0,0.974,1.000
81,Phylloscopus collybita,42,5,13,0.976,0.999
21,Caprimulgus europaeus,41,6,13,0.986,1.000
34,Cuculus canorus,34,2,8,0.973,0.999
18,Branta canadensis,33,4,0,0.938,0.989
86,Pica pica,30,8,8,0.944,0.998
3,Acrocephalus scirpaceus,30,9,1,0.914,0.989
7,Alcedo atthis,28,12,0,0.967,1.000
96,Regulus regulus,27,5,4,0.949,0.999
41,Cygnus atratus,24,5,0,0.977,0.998
63,Lanius collurio,24,3,4,0.939,0.994
4,Aegithalos caudatus,23,2,0,0.960,0.999

### Hidden species — detected by BirdNET but not declared in XC `also`

`n_undeclared` = how many BirdNET detections of this species were in recordings where the recordist did **not** list it (neither as primary nor in `also`). High values = systematically under-reported.

In [89]:
bn["hidden"].head(40)

,detected_species,n_detections,n_recordings,n_undeclared,mean_conf,max_conf
0,Regulus ignicapilla,226,21,33,0.977,1.000
1,Cyanistes caeruleus,77,8,21,0.946,0.999
2,Locustella luscinioides,444,20,13,0.988,1.000
3,Caprimulgus europaeus,41,6,13,0.986,1.000
4,Dendrocopos major,157,9,13,0.943,0.997
5,Phylloscopus collybita,42,5,13,0.976,0.999
6,Corvus cornix,11,8,11,0.891,0.948
7,Sylvia atricapilla,60,15,11,0.936,0.996
8,Poecile palustris,77,9,10,0.974,1.000
9,Parus major,244,21,10,0.966,1.000
10,Acrocephalus palustris,214,17,9,0.932,0.999
11,Cisticola juncidis,118,8,9,0.987,1.000
12,Saxicola rubicola,8,4,8,0.950,0.991
13,Troglodytes troglodytes,18,4,8,0.941,0.998
14,Cuculus canorus,34,2,8,0.973,0.999
15,Pica pica,30,8,8,0.944,0.998
16,Corvus corone,14,4,7,0.899,0.947
17,Fulica atra,21,5,7,0.963,0.998
18,Sylvia borin,469,11,7,0.972,1.000
19,Hippolais polyglotta,284,27,7,0.965,1.000
20,Ardea herodias,6,1,6,0.891,0.944
21,Certhia brachydactyla,6,3,6,0.910,0.977
22,Picus viridis,97,14,6,0.982,1.000
23,Dryobates minor,5,4,5,0.927,0.959
24,Pnoepyga pusilla,5,1,5,0.906,0.984
25,Dendrocoptes medius,188,23,5,0.980,1.000
26,Alauda arvensis,94,8,4,0.972,1.000
27,Lanius collurio,24,3,4,0.939,0.994
28,Regulus regulus,27,5,4,0.949,0.999
29,Lophophanes cristatus,54,8,4,0.964,1.000
30,Falco tinnunculus,169,9,4,0.978,1.000
31,Psittacula krameri,152,23,3,0.955,0.998
32,Sitta europaea,3,3,3,0.917,0.925
33,Garrulus glandarius,16,6,3,0.968,0.998
34,Anthus spinoletta,3,2,3,0.902,0.937
35,Urosphena squameiceps,3,2,3,0.936,0.958
36,Strix aluco,3,1,3,0.915,0.934
37,Erithacus rubecula,2,1,2,0.930,0.969
38,Chroicocephalus novaehollandiae,2,1,2,0.920,0.939
39,Luscinia megarhynchos,2,1,2,0.869,0.880

# All area species — split by source

For each species in the area, three mutually exclusive per-recording counts:

- **`xc_primary`** — recordings whose declared primary species is this one
- **`xc_also`** — recordings that list this species in `also`
- **`birdnet_only`** — recordings where BirdNET detected this species and the recordist did **not** list it (neither primary nor in `also`)

Filter: `xc_primary + xc_also + birdnet_only ≥ MIN_RECORDINGS`. Sorted by total desc.

> The `birdnet_only` column is sparse unless `MAX_BIRDNET_RECORDINGS` covers most of the area.

In [90]:
from building.analysis import combined_species_table

combined = combined_species_table(area_df, bn["detections"], min_recordings=MIN_RECORDINGS)
print(f"{len(combined)} species (≥ {MIN_RECORDINGS} recordings of any source)")
combined

38 species (≥ 10 recordings of any source)

                 scientific_name  xc_primary  xc_also  birdnet_only  total
0           Hippolais polyglotta          26        0             5     31
1             Psittacula krameri          21        5             3     29
2                    Parus major          22        4             3     29
3              Anthus spinoletta          26        0             2     28
4            Dendrocoptes medius          22        0             3     25
5               Curruca communis          22        0             2     24
6              Fringilla coelebs          10       11             2     23
7             Sylvia atricapilla          14        4             4     22
8            Regulus ignicapilla          20        0             2     22
9          Certhia brachydactyla          18        1             3     22
10       Troglodytes troglodytes          12        6             3     21
11       Locustella luscinioides          15        0             5     20
12        Acrocephalus palustris          13        0             5     18
13        Phylloscopus collybita           5       10             2     17
14             Muscicapa striata          17        0             0     17
15             Locustella naevia          13        3             1     17
16                     Tyto alba          17        0             0     17
17            Erithacus rubecula          13        3             1     17
18          Corvus corone corone          16        0             0     16
19              Acanthis cabaret          15        0             0     15
20             Turdus philomelos          11        3             0     14
21                 Turdus merula           8        6             0     14
22                 Alcedo atthis          14        0             0     14
23             Poecile palustris           6        4             4     14
24                 Picus viridis           9        0             5     14
25                 Corvus corone           3        8             3     14
26                 Athene noctua          13        0             0     13
27                Sitta europaea           9        1             3     13
28            Cisticola juncidis          11        0             1     12
29                Curruca undata          12        0             0     12
30                  Sylvia borin           7        0             4     11
31                     Pica pica           2        3             5     10
32         Luscinia megarhynchos           7        2             1     10
33  Anthus spinoletta spinoletta          10        0             0     10
34       Acrocephalus scirpaceus           7        2             1     10
35           Cyanistes caeruleus           6        1             3     10
36             Dendrocopos major           7        0             3     10
37             Falco tinnunculus           9        0             1     10